#!/usr/bin/env python3
"""
Generate app/src/states.generated.ts from the state descriptors.

    uv run python3 pipeline/build_app_states.py

The app never hand-maintains a per-state list. This reads every StateDescriptor registered in
build_state.py and emits the StateConfig array the app consumes, so a state is added to the app
by writing its descriptor (pipeline/states/<name>.py) and re-running `make app-states` — never
by editing app/src/states.ts. That is what makes the app scale to N states as configuration
rather than code. The reuse gate still applies in the app: uncleared states are marked here and
filtered out of production builds (see app/src/states.ts).
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_state import STATES, load_descriptor

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_OUT = os.path.join(_ROOT, "app", "src", "states.generated.ts")


def to_config(d):
    """Map a StateDescriptor to the app's StateConfig shape."""
    cfg = {
        "slug": d.slug,
        "name": d.state,
        "dot": d.dot,
        # Washington's data is at the legacy root path; every other state is namespaced.
        "dataBase": "data" if d.slug == "wa" else f"data/{d.slug}",
        "corpusLabel": d.corpus_label or f"{d.dot} Standard Specifications",
        "edition": d.latest,
        "history": d.history,
        "requirements": d.requirements,
        "ask": d.ask,
        "semantic": d.semantic,
    }
    if d.demo_section:
        cfg["demoSection"] = d.demo_section
    if d.reuse != "public":
        cfg["uncleared"] = True
    return cfg


def main():
    configs = [to_config(load_descriptor(slug)) for slug in STATES]
    body = ",\n".join("  " + json.dumps(c) for c in configs)
    ts = (
        "// GENERATED by pipeline/build_app_states.py — do not edit. Run `make app-states`.\n"
        "// Derived from the pipeline/states/*.py descriptors: a state is added as a\n"
        "// descriptor, not by editing the app.\n"
        'import type { StateConfig } from "./states";\n\n'
        f"export const ALL_STATES: StateConfig[] = [\n{body},\n];\n"
    )
    with open(_OUT, "w") as handle:
        handle.write(ts)
    print(f"wrote {_OUT}: {len(configs)} states ({', '.join(c['slug'] for c in configs)})")


if __name__ == "__main__":
    main()
