// GENERATED by pipeline/build_app_states.py — do not edit. Run `make app-states`.
// Derived from the pipeline/states/*.py descriptors: a state is added as a
// descriptor, not by editing the app.
import type { StateConfig } from "./states";

export const ALL_STATES: StateConfig[] = [
  {"slug": "wa", "name": "Washington", "dot": "WSDOT", "dataBase": "data", "corpusLabel": "WSDOT Standard Specifications \u00b7 M 41-10", "edition": 2026, "history": true, "requirements": true, "ask": true, "semantic": true, "demoSection": "1-09.7"},
  {"slug": "nd", "name": "North Dakota", "dot": "NDDOT", "dataBase": "data/nd", "corpusLabel": "NDDOT Standard Specifications for Road and Bridge Construction", "edition": 2025, "history": false, "requirements": false, "ask": false, "semantic": false, "uncleared": true},
  {"slug": "de", "name": "Delaware", "dot": "DelDOT", "dataBase": "data/de", "corpusLabel": "DelDOT Standard Specifications for Road and Bridge Construction", "edition": 2026, "history": false, "requirements": false, "ask": false, "semantic": false, "uncleared": true},
  {"slug": "id", "name": "Idaho", "dot": "ITD", "dataBase": "data/id", "corpusLabel": "ITD Standard Specifications for Highway Construction", "edition": 2023, "history": false, "requirements": false, "ask": false, "semantic": false, "uncleared": true},
  {"slug": "mo", "name": "Missouri", "dot": "MoDOT", "dataBase": "data/mo", "corpusLabel": "MoDOT Standard Specifications for Highway Construction", "edition": 2026, "history": false, "requirements": false, "ask": false, "semantic": false, "uncleared": true},
  {"slug": "pa", "name": "Pennsylvania", "dot": "PennDOT", "dataBase": "data/pa", "corpusLabel": "PennDOT Specifications \u00b7 Publication 408", "edition": 2026, "history": false, "requirements": false, "ask": false, "semantic": false, "uncleared": true},
  {"slug": "co", "name": "Colorado", "dot": "CDOT", "dataBase": "data/co", "corpusLabel": "CDOT Standard Specifications for Road and Bridge Construction", "edition": 2025, "history": false, "requirements": false, "ask": false, "semantic": false, "uncleared": true},
  {"slug": "tn", "name": "Tennessee", "dot": "TDOT", "dataBase": "data/tn", "corpusLabel": "TDOT Standard Specifications for Road and Bridge Construction", "edition": 2026, "history": false, "requirements": false, "ask": false, "semantic": false, "uncleared": true},
  {"slug": "va", "name": "Virginia", "dot": "VDOT", "dataBase": "data/va", "corpusLabel": "VDOT Road and Bridge Specifications", "edition": 2020, "history": false, "requirements": false, "ask": false, "semantic": false, "uncleared": true},
  {"slug": "fl", "name": "Florida", "dot": "FDOT", "dataBase": "data/fl", "corpusLabel": "FDOT Standard Specifications for Road and Bridge Construction", "edition": 2026, "history": false, "requirements": false, "ask": false, "semantic": false, "uncleared": true},
  {"slug": "me", "name": "Maine", "dot": "MaineDOT", "dataBase": "data/me", "corpusLabel": "MaineDOT Standard Specifications", "edition": 2026, "history": false, "requirements": false, "ask": false, "semantic": false, "uncleared": true},
  {"slug": "ne", "name": "Nebraska", "dot": "NDOT", "dataBase": "data/ne", "corpusLabel": "NDOT Standard Specifications for Highway Construction", "edition": 2017, "history": false, "requirements": false, "ask": false, "semantic": false, "uncleared": true},
  {"slug": "oh", "name": "Ohio", "dot": "ODOT", "dataBase": "data/oh", "corpusLabel": "ODOT Construction and Material Specifications", "edition": 2023, "history": false, "requirements": false, "ask": false, "semantic": false, "uncleared": true},
  {"slug": "sc", "name": "South Carolina", "dot": "SCDOT", "dataBase": "data/sc", "corpusLabel": "SCDOT Standard Specifications for Highway Construction", "edition": 2025, "history": false, "requirements": false, "ask": false, "semantic": false, "uncleared": true},
  {"slug": "ms", "name": "Mississippi", "dot": "MDOT", "dataBase": "data/ms", "corpusLabel": "MDOT Standard Specifications for Road and Bridge Construction", "edition": 2017, "history": false, "requirements": false, "ask": false, "semantic": false, "uncleared": true},
  {"slug": "wv", "name": "West Virginia", "dot": "WVDOH", "dataBase": "data/wv", "corpusLabel": "WVDOH Standard Specifications Roads and Bridges", "edition": 2023, "history": false, "requirements": false, "ask": false, "semantic": false, "uncleared": true},
  {"slug": "ri", "name": "Rhode Island", "dot": "RIDOT", "dataBase": "data/ri", "corpusLabel": "RIDOT Standard Specifications (Blue Book)", "edition": 2026, "history": false, "requirements": false, "ask": false, "semantic": false, "uncleared": true},
  {"slug": "md", "name": "Maryland", "dot": "MDOT SHA", "dataBase": "data/md", "corpusLabel": "MDOT SHA Standard Specifications for Construction and Materials", "edition": 2025, "history": false, "requirements": false, "ask": false, "semantic": false, "uncleared": true},
];
